### ISSUE TITLE
Integrating Jitsi into mobile apps

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-meta#92]
* Add native jitsi SDK to apps
* Determine whether to call a freeswitch or jitsi instance in a room based on room state (defaulting to jitsi)
  * @superdump can you flesh out your thoughts on a simple room state to specify the focus for a given room?
* Hook up video/voip call buttons in group rooms to default to calling Jitsi when desired.
* Unlike web, we don't implement this as a widget, given it's native code in the app.

**Comment by manuroe** [comment]
jitsi sdks: https://github.com/jitsi/jitsi-meet

**Comment by superdump** [comment]
We shouldn't make Jitsi the default until all the main Riot clients support its use so that we can do a switch all at once. I would suggest that the call buttons remain hooked up to FreeSwitch until we switch over to Jitsi fully.

Until we switch over to Jitsi fully, we should both check for `@fs_*:matrix.org` users indicating an ongoing FreeSwitch conference in a room as we already are, and now also check the room state for Jitsi and use that information to present that a call is ongoing in the room and to join it if desired.

I'll respond again in a bit with the room state for Jitsi.

**Comment by superdump** [comment]
The Jitsi widget would have room state as in this document: https://docs.google.com/document/d/1TiWNDcEOULeRYQpkJHQDjgIW32ohIJSi5MKv9oRdzCo/edit

So it would have `content.type` as `jitsi` and `content.url` would be something like (literally) `https://example.com/scalar/api/widgets/jitsi.html?confId=aFakeID&isAudioConf=false&displayName=$matrix_display_name&avatarUrl=$matrix_avatar_url&email=$matrix_user_id`. Where `aFakeID` would be an actual conference ID that can be used on a particular Jitsi Meet deployment. `isAudioConf=true` would configure an audio-only conference or that this client joins with 'muted' video. The rest of the parameters should be self-explanatory, although we're passing the Matrix user ID as the email because that seemed to make the most sense for cross-correlation as we won't actually use the email address.

**Comment by manuroe** [comment]
Done on iOS. Except:
- user name and avatar are not customised in the jitsi-meet view (https://github.com/jitsi/jitsi-meet/issues/1880)
- there is no pod for the jitsi-meet iOS sdk (https://github.com/jitsi/jitsi-meet/issues/1854). So I built it from their jitsi-meet_2369 tag
